[package]
name = "pof-earth-downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
ureq = "2.7.1" #check surf isahc and alternatives from ureq web
